def Myname():
    print("&&&&&&&&&&                               %        %                               ##########")
    print("        &                                %        %                                       # ")
    print("       &                                 %        %                                      #  ")
    print("      &                                  %        %                                     #   ") 
    print("     &                                   %%%%%%%%%%                                    #    ")
    print("    &                                    %        %                                   #     ")
    print("   &                                     %        %                                  #      ")
    print("  &                                      %        %                                 #       ")
    print(" &                                       %        %                                #        ")
    print("&&&&&&&&&&                               %        %                               ##########")
Myname()    
